In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix,accuracy_score
from ann_visualizer.visualize import ann_viz

Using TensorFlow backend.


In [2]:
dataframeX = pd.read_csv('character-predictions.csv', usecols= [7, 16, 17, 18, 19, 20, 25, 26, 28, 29, 30, 31])
dataframeY = pd.read_csv('character-predictions.csv', usecols=[32])

In [3]:
print(dataframeX.head(5))
print(dataframeY.head(5))

   male  book1  book2  book3  book4  book5  isMarried  isNoble  \
0     1      0      0      0      0      0          0        0   
1     1      1      1      1      1      1          1        1   
2     1      0      0      0      1      0          0        1   
3     0      0      0      0      0      0          1        1   
4     0      0      0      0      1      0          1        1   

   numDeadRelations  boolDeadRelations  isPopular  popularity  
0                11                  1          1    0.605351  
1                 1                  1          1    0.896321  
2                 0                  0          0    0.267559  
3                 0                  0          0    0.183946  
4                 0                  0          0    0.043478  
   isAlive
0        0
1        1
2        1
3        0
4        1


In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(dataframeX.values, dataframeY.values, test_size = 0.2)

In [5]:
print(X_train,X_test)

(array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.05351171],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.02675585],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01337793],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01337793],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.16053512],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01003344]]), array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01003344],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.19063545],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04013378],
       [1.        , 0.        , 0

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train,X_test)

(array([[ 0.78471906, -0.49678453, -0.78151522, ..., -0.28907691,
        -0.25499795, -0.2278903 ],
       [ 0.78471906, -0.49678453,  1.2795656 , ..., -0.28907691,
        -0.25499795, -0.39529137],
       [ 0.78471906, -0.49678453, -0.78151522, ..., -0.28907691,
        -0.25499795, -0.47899191],
       ...,
       [-1.27434141, -0.49678453, -0.78151522, ..., -0.28907691,
        -0.25499795, -0.47899191],
       [-1.27434141, -0.49678453,  1.2795656 , ..., -0.28907691,
        -0.25499795,  0.44171397],
       [-1.27434141, -0.49678453, -0.78151522, ..., -0.28907691,
        -0.25499795, -0.49991704]]), array([[-1.27434141, -0.49678453, -0.78151522, ..., -0.28907691,
        -0.25499795, -0.49991704],
       [-1.27434141, -0.49678453,  1.2795656 , ..., -0.28907691,
        -0.25499795,  0.63004017],
       [ 0.78471906, -0.49678453, -0.78151522, ..., -0.28907691,
        -0.25499795, -0.56269244],
       ...,
       [ 0.78471906, -0.49678453, -0.78151522, ..., -0.28907691,
        

In [8]:
model = Sequential()

In [9]:
model.add(Dense(15, input_dim=12, activation='relu'))

In [10]:
model.add(Dense(50, activation='relu'))

In [11]:
model.add(Dense(9, activation='relu'))

In [12]:
model.add(Dense(8, activation='relu'))

In [13]:
model.add(Dense(5, activation='relu'))

In [14]:
model.add(Dense(1, activation='sigmoid'))

In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 15)                195       
_________________________________________________________________
dense_2 (Dense)              (None, 50)                800       
_________________________________________________________________
dense_3 (Dense)              (None, 9)                 459       
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 80        
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 45        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 6         
Total params: 1,585
Trainable params: 1,585
Non-trainable params: 0
_________________________________________________________________


In [405]:
#Model 1 - Adam - Mean Squared Error

In [406]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [407]:
tbCallBack = keras.callbacks.TensorBoard(log_dir='/tmp/keras_logs', write_graph=True)

In [408]:
model.fit(X_train, Y_train, epochs=100, batch_size=50,  verbose=1, callbacks=[tbCallBack])

Epoch 1/100
1556/1556 [==============================] - 0s 156us/step - loss: 0.2559 - acc: 0.4602
Epoch 2/100
1556/1556 [==============================] - 0s 34us/step - loss: 0.2421 - acc: 0.7513
Epoch 3/100
1556/1556 [==============================] - 0s 37us/step - loss: 0.2313 - acc: 0.7603
Epoch 4/100
1556/1556 [==============================] - 0s 44us/step - loss: 0.2121 - acc: 0.7539
Epoch 5/100
1556/1556 [==============================] - 0s 34us/step - loss: 0.1827 - acc: 0.7616
Epoch 6/100
1556/1556 [==============================] - 0s 40us/step - loss: 0.1686 - acc: 0.7629
Epoch 7/100
1556/1556 [==============================] - 0s 40us/step - loss: 0.1610 - acc: 0.7706
Epoch 8/100
1556/1556 [==============================] - 0s 49us/step - loss: 0.1572 - acc: 0.7686
Epoch 9/100
1556/1556 [==============================] - 0s 47us/step - loss: 0.1542 - acc: 0.7834
Epoch 10/100
1556/1556 [==============================] - 0s 40us/step - loss: 0.1524 - acc: 0.7879
Epoch 11

In [409]:
model.save('NN_meansqerror.h5')

In [410]:
Y_pred = model.predict(X_test)
Y_pred = (Y_pred > 0.5)

In [411]:
cm = confusion_matrix(Y_test, Y_pred)
print("\nConfusion Matrix:")
print(cm)


Confusion Matrix:
[[ 30  60]
 [ 25 275]]


In [412]:
acs = accuracy_score(Y_test, Y_pred)
print("\nAccuracy Score: %.2f%%" % (acs * 100))


Accuracy Score: 78.21%


In [16]:
#Model 2 - Adam - Binary Cross Entropy

In [17]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [18]:
tbCallBack = keras.callbacks.TensorBoard(log_dir='/tmp/keras_logs', write_graph=True)

In [19]:
model.fit(X_train, Y_train, epochs=100, batch_size=50, verbose=1, callbacks=[tbCallBack])

Epoch 1/100
1556/1556 [==============================] - 0s 107us/step - loss: 0.6319 - acc: 0.7339
Epoch 2/100
1556/1556 [==============================] - 0s 26us/step - loss: 0.5669 - acc: 0.7339
Epoch 3/100
1556/1556 [==============================] - 0s 27us/step - loss: 0.5337 - acc: 0.7339
Epoch 4/100
1556/1556 [==============================] - 0s 29us/step - loss: 0.5122 - acc: 0.7339
Epoch 5/100
1556/1556 [==============================] - 0s 29us/step - loss: 0.5028 - acc: 0.7339
Epoch 6/100
1556/1556 [==============================] - 0s 28us/step - loss: 0.4960 - acc: 0.7339
Epoch 7/100
1556/1556 [==============================] - 0s 28us/step - loss: 0.4928 - acc: 0.7339
Epoch 8/100
1556/1556 [==============================] - 0s 28us/step - loss: 0.4874 - acc: 0.7339
Epoch 9/100
1556/1556 [==============================] - 0s 27us/step - loss: 0.4842 - acc: 0.7506
Epoch 10/100
1556/1556 [==============================] - 0s 28us/step - loss: 0.4824 - acc: 0.7706
Epoch 11

1556/1556 [==============================] - 0s 26us/step - loss: 0.3743 - acc: 0.8413
Epoch 84/100
1556/1556 [==============================] - 0s 26us/step - loss: 0.3760 - acc: 0.8329
Epoch 85/100
1556/1556 [==============================] - 0s 28us/step - loss: 0.3715 - acc: 0.8419
Epoch 86/100
1556/1556 [==============================] - 0s 29us/step - loss: 0.3783 - acc: 0.8387
Epoch 87/100
1556/1556 [==============================] - 0s 26us/step - loss: 0.3714 - acc: 0.8380
Epoch 88/100
1556/1556 [==============================] - 0s 38us/step - loss: 0.3778 - acc: 0.8323
Epoch 89/100
1556/1556 [==============================] - 0s 32us/step - loss: 0.3730 - acc: 0.8380
Epoch 90/100
1556/1556 [==============================] - 0s 34us/step - loss: 0.3705 - acc: 0.8400
Epoch 91/100
1556/1556 [==============================] - 0s 29us/step - loss: 0.3670 - acc: 0.8400
Epoch 92/100
1556/1556 [==============================] - 0s 27us/step - loss: 0.3672 - acc: 0.8419
Epoch 93/100


In [20]:
model.save('NN_binarycrossentropy.h5')

In [21]:
Y_pred = model.predict(X_test)
Y_pred = (Y_pred > 0.5)

In [22]:
acs = accuracy_score(Y_test, Y_pred)
print("\nAccuracy Score: %.2f%%" % (acs * 100))


Accuracy Score: 84.36%


In [23]:
def predictor(names):
    df = pd.read_csv('character-predictions.csv', usecols= [5,7, 16, 17, 18, 19, 20, 25, 26, 28, 29, 30, 31])
    sur=[]
    dead=[]
    for name in names:
        parameters = df.loc[df['name'] == name]
        parameters.drop(parameters.columns[0], axis=1, inplace=True)
        inputFeature = np.asarray(parameters).reshape(1, 12)
        raw_prediction = model.predict(inputFeature)[0][0]
        if raw_prediction > 0.5:
            sur.append(name)
        else:
            dead.append(name)
            
    print('Survivors :')
    print(sur)
    print('')
    print('Dead :')
    print(dead)
    print('')

In [24]:
df = pd.read_csv('character-predictions.csv', usecols= [5,7, 16, 17, 18, 19, 20, 25, 26, 28, 29, 30, 31])

Lannisters=['Tyrion Lannister','Jaime Lannister','Cersei Lannister']
print('\t\t\t\tSurviving Lannisters')
predictor(Lannisters)
print('===========================================')
Starks=['Arya Stark','Sansa Stark','Brandon Stark']
print('\t\t\t\tSurviving Starks')
predictor(Starks)
print('===========================================')
Targaryens=['Daenerys Targaryen','Jon Snow']
print('\t\t\t\tSurviving Targaryens')
predictor(Targaryens)
print('===========================================')
Misc=['Samwell Tarly','Daario Naharis','Jorah Mormont','Missandei','Grey Worm','Gilly','Melisandre',\
      'Asha Greyjoy','Theon Greyjoy','Gendry','Varys','Sandor Clegane']
print('\t\t\t\tOther Survivers')
predictor(Misc)
print('===========================================')

				Surviving Lannisters


/home/kash/.local/lib/python2.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


Survivors :
['Cersei Lannister']

Dead :
['Tyrion Lannister', 'Jaime Lannister']

				Surviving Starks
Survivors :
['Arya Stark', 'Sansa Stark']

Dead :
['Brandon Stark']

				Surviving Targaryens
Survivors :
['Daenerys Targaryen']

Dead :
['Jon Snow']

				Other Survivers
Survivors :
['Samwell Tarly', 'Daario Naharis', 'Jorah Mormont', 'Missandei', 'Grey Worm', 'Melisandre', 'Asha Greyjoy', 'Varys']

Dead :
['Gilly', 'Theon Greyjoy', 'Gendry', 'Sandor Clegane']



In [26]:
ann_viz(model, view=True, filename='network.gv', title='GoT CNN')